import './global.css'
import type { Metadata } from 'next'
import { NextUIProvider } from '../providers/NextUIProvider'
import { PlayerControlProvider } from '../providers/PlayerControlProvider'

export const metadata: Metadata = {
  title: 'Next Music',
  description: 'Generated by create Next Music',
}

export default function AppLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="light">
      <body>
        <NextUIProvider>
          <PlayerControlProvider>
            {children}
          </PlayerControlProvider>
        </NextUIProvider>
      </body>
    </html>
  )
}
