import './globals.css'
import type { Metadata } from 'next'
import { Providers } from './providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props) {
  return (
    <html lang="en" className="dark">
      <body>
        <Providers>
          {props.children}
        </Providers>
      </body>
    </html>
  )
}
